
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/prod_m3_db
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
